var publicaciones_to_show=[
  {
    'post_id':"lucky",
    'post_img':"img/galeria/lucky/a_1_by_unknow.jpg",
    'post_url':'post.html?id=lucky',
    'post_target':'',
    'post_date':'2013-02-10T19:57:30Z',
    'post_edit':'2019-03-19T23:24:33Z',
    'post_title':'Lucky 2013❤2019',
    'post_galeria':'lucky',
    'post_in':'Esta web',
    'zmdi':'favorite',
    'zmdi_color':'bg-hotpink',
    'post_excerpt':'Lo extraño mucho, era muy buen gato. Entendía algunas cosas y muy regalón si lo pillabas de buen humor.',
    'post_text':'Una personalidad muy calmada, sin contar cuando quería salir y no podía o las clásicas locuras nocturnas de los gatos.'
  },
  {
    'post_id':"katara",
    'post_img':"img/galeria/katara/IMG_0011.jpg",
    'post_url':'post.html?id=katara',
    'post_target':'',
    'post_date':'2020-06-15T20:27:15Z',
    'post_edit':'2022-12-08T14:12:14Z',
    'post_title':'Katara 2020❤',
    'post_galeria':'katara',
    'post_in':'Esta web',
    'zmdi':'favorite',
    'zmdi_color':'bg-hotpink',
    'post_excerpt':'Katara Luna nació en marzo del 2020 y la adopte en mayo. El primer año vivió acompañándome en la casa de mi familia.',
    'post_text':'Hoy ya tiene una "hermana" adoptiva con 1 año de diferencia, la <a href="post.html?id=nami" style="color:blue;text-decoration: underline;">Nami</a>.'
  },
  {
    'post_id':"nami",
    'post_img':"img/galeria/nami/IMG-20210926-WA0000.jpg",
    'post_url':'post.html?id=nami',
    'post_target':'',
    'post_date':'2021-09-27T16:57:42Z',
    //'post_edit':'2022-06-05T14:12:14Z',
    'post_title':'Nami 2021❤',
    'post_galeria':'nami',
    'post_in':'Esta web',
    'zmdi':'favorite',
    'zmdi_color':'bg-hotpink',
    'post_excerpt':'Nami Ñami Chuletas...'
  },
  {
    'post_id':"katara_nami",
    'post_img':"img/galeria/katara_nami/katara-y-nami.jpg",
    'post_url':'post.html?id=katara_nami',
    'post_target':'',
    'post_date':'2022-12-20T18:46:11Z',
    //'post_edit':'2022-06-05T14:12:14Z',
    'post_title':'Galeria Katara y Nami ❤',
    'post_galeria':'katara_nami',
    'post_in':'Esta web',
    'zmdi':'favorite',
    'zmdi_color':'bg-hotpink',
    'post_excerpt':'Aventuras de Katara Luna y Nami Ñami Chuletas...'
  },
  {
    'post_id':"arte_dani",
    'post_img':"img/galeria/arte_dani/a3514c9d-2f31-49e5-9332-d24c32ca7dc5.jpg",
    'post_url':'post.html?id=arte_dani',
    'post_target':'',
    'post_date':'2019-05-23T17:04:49Z',
    //'post_edit':'2022-06-05T14:12:14Z',
    'post_title':'El genial arte de Dani!',
    'post_galeria':'arte_dani',
    'post_in':'Esta web',
    'zmdi':'accounts',
    'zmdi_color':'bg-hotpink',
    'post_excerpt':'A continuación podrán disfrutar de el maravilloso talento de Dani, su habilidad artística, creativa y varias más nunca me dejan de sorprender.',
    'post_text':' Estoy seguro que conquistara sus metas, es alguien que merece cosas buenas en exceso.'
  },

];
